### ISSUE TITLE
Too Many Sam's

### ISSUE THREAD

**Issue by g-nym** [ANU-RSES-Education/EMSC-4033-2022-assignment-Group1#11]
In our main folder, I currently see three folders pertaining to Sam. There is a "Sam L", "Sam", and "User 4" is described as 'Sam's Notebook'.

**Comment by Samlewis99** [comment]
Hi Gwen, When you merged your pull request you have created these additional folders. The correct folder is Sam L, the rest will need to be deleted. Along with the second Gwen folder

**Comment by Samlewis99** [comment]
I assume once Xulu's work is committed we will get even more double ups- we can delete these once she has committed them.

**Comment by Samlewis99** [comment]
@XuluLin, if you only push from your name folder rather than the parent folder we won't get any double ups. Cheers

**Comment by g-nym** [comment]
Thanks for walking this through Sam -- sounds good. If I recall, you're happy to do the final folder clean-up once all our commits are approved?

**Comment by Samlewis99** [comment]
I have put a push through with cleaned structure if somebody could approve @g-nym @XuluLin

**Comment by g-nym** [comment]
Issue closed. Folders look shiny and tidy!
