### ISSUE TITLE
File format

### ISSUE THREAD

**Issue by Samlewis99** [ANU-RSES-Education/EMSC-4033-2022-assignment-Group1#15]
@XuluLin the file format in your folder name has two test folders. one named test and another named test 1. Can you delete one of these and push changes?

**Comment by XuluLin** [comment]
I just deleted my folder and pushed it. How do I merge it to main? Or do you have to review it first? It is pull request #16

**Comment by Samlewis99** [comment]
we need one reviewer so I will merge for you!
